export const mockApplications = [
  {
    id: 1,
    company: "Google",
    jobTitle: "Frontend Developer",
    source: "LinkedIn",
    dateApplied: "2025-09-15",
    status: "Interview",
    automated: true,
    salary: "₱80,000–₱100,000",
    location: "Remote",
    recruiter: { name: "Anna Reyes", email: "anna@google.com" },
    tags: ["High Priority", "Tech"],
    notes: "Scheduled 2nd round interview",
    history: [
      { date: "2025-09-10", status: "Applied" },
      { date: "2025-09-15", status: "Interview" },
    ],
  },
  {
    id: 2,
    company: "Microsoft",
    jobTitle: "Backend Engineer",
    source: "JobStreet",
    dateApplied: "2025-09-20",
    status: "Applied",
    automated: false,
    salary: "₱90,000–₱110,000",
    location: "Hybrid - Makati",
    recruiter: { name: "Mark Santos", email: "mark@microsoft.com" },
    tags: ["Backend", "Enterprise"],
    notes: "Waiting for initial HR screening",
    history: [{ date: "2025-09-20", status: "Applied" }],
  },
  {
    id: 3,
    company: "Accenture",
    jobTitle: "Full Stack Developer",
    source: "Indeed",
    dateApplied: "2025-08-30",
    status: "Rejected",
    automated: true,
    salary: "₱70,000–₱85,000",
    location: "Hybrid - BGC",
    recruiter: { name: "Elaine Tan", email: "elaine@accenture.com" },
    tags: ["Rejected", "Follow-up"],
    notes: "Did not pass technical assessment",
    history: [
      { date: "2025-08-25", status: "Applied" },
      { date: "2025-08-28", status: "Interview" },
      { date: "2025-08-30", status: "Rejected" },
    ],
  },
  {
    id: 4,
    company: "Grab Philippines",
    jobTitle: "UI/UX Designer",
    source: "Kalibrr",
    dateApplied: "2025-09-10",
    status: "Hired",
    automated: false,
    salary: "₱75,000–₱90,000",
    location: "Remote",
    recruiter: { name: "Carlos Mendoza", email: "carlos@grab.com" },
    tags: ["Design", "Offer Accepted"],
    notes: "Accepted offer; start date October 1",
    history: [
      { date: "2025-09-05", status: "Applied" },
      { date: "2025-09-08", status: "Interview" },
      { date: "2025-09-10", status: "Hired" },
    ],
  },
  {
    id: 5,
    company: "Canva",
    jobTitle: "Product Designer",
    source: "LinkedIn",
    dateApplied: "2025-09-22",
    status: "Shortlisted",
    automated: true,
    salary: "₱100,000–₱130,000",
    location: "Hybrid - Manila",
    recruiter: { name: "Tricia Gomez", email: "tricia@canva.com" },
    tags: ["Design", "Creative"],
    notes: "Received email for portfolio review",
    history: [
      { date: "2025-09-22", status: "Applied" },
      { date: "2025-09-25", status: "Shortlisted" },
    ],
  },
  {
    id: 6,
    company: "Figma",
    jobTitle: "Visual Designer",
    source: "Dribbble",
    dateApplied: "2025-09-28",
    status: "Applied",
    automated: false,
    salary: "₱85,000–₱100,000",
    location: "Remote",
    recruiter: { name: "Julia Tan", email: "julia@figma.com" },
    tags: ["Design", "UI"],
    notes: "Pending feedback from HR",
    history: [{ date: "2025-09-28", status: "Applied" }],
  },
];
